require:
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 50
Metrics/ModuleLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 200
Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
