include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "ruby_gems/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
max_files: 5000
